// <auto-generated />
using System;
using Ferris_Bakes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferris_Bakes.Migrations.FerrisBakes
{
    [DbContext(typeof(FerrisBakesContext))]
    [Migration("20211115095514_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ferris_Bakes.Models.CartItemModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.CustomOrderModel", b =>
                {
                    b.Property<int>("orderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Frosting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("fillFlavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("filling")
                        .HasColumnType("bit");

                    b.Property<string>("flavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.HasKey("orderNumber");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.ReciepeBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ReciepeBookId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReciepeBookId");

                    b.ToTable("ReciepeBook");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.ReciepeModel", b =>
                {
                    b.Property<int>("ReciepeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ReciepeBookId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReciepeNumber");

                    b.HasIndex("ReciepeBookId");

                    b.ToTable("Reciepes");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.SetOrderModel", b =>
                {
                    b.Property<int>("BakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BakeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BakeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FillFlavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frosting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("BakeID");

                    b.ToTable("SetOrder");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.CartItemModel", b =>
                {
                    b.HasOne("Ferris_Bakes.Models.SetOrderModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.ReciepeBook", b =>
                {
                    b.HasOne("Ferris_Bakes.Models.ReciepeBook", null)
                        .WithMany("Chapters")
                        .HasForeignKey("ReciepeBookId");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.ReciepeModel", b =>
                {
                    b.HasOne("Ferris_Bakes.Models.ReciepeBook", null)
                        .WithMany("Reciepes")
                        .HasForeignKey("ReciepeBookId");
                });

            modelBuilder.Entity("Ferris_Bakes.Models.ReciepeBook", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Reciepes");
                });
#pragma warning restore 612, 618
        }
    }
}
